repository:
  name: asdf-hashicorp
  description: HashiCorp tools plugin for asdf version manager
  homepage: https://github.com/asdf-vm/asdf
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  topics: asdf, version-manager, asdf-plugin, hashicorp, consul, nomad, packer, terraform, vault 
labels:
- name: bug
  color: CC0000
- name: feature
  color: 336699
collaborators:
- username: nikolay
  permission: admin
